applications:
    app:
        type: nodejs:20
        web:
            commands:
                start: node server.js
            locations:
                /:
                    passthru: true

routes:
    "https://{default}/":
        type: upstream
        upstream: "app:http"
        cache:
            enabled: true
            default_ttl: 300
    "http://{default}/":
        type: redirect
        to: "https://{default}/"
